### ISSUE TITLE
Section: Python from the Shell

### ISSUE THREAD

**Issue by markroepke** [uc-python/intermediate-python-datasci#10]

**Comment by eswan18** [comment]
Ready for review, @markroepke

**Comment by markroepke** [comment]
The structure and material covered in this looks good. A couple questions/comments:
 
1. It may be worth mentioning in the `.py` file section that notebooks can be exported directly to `.py` files and that the Notebook's markdown will appear as commented text.
2. Are we sure that Python 3 will run when `python` is called on all of their machines? I am worried about Python 2 being the default and/or it not working on Windows.

**Comment by eswan18** [comment]
Good thoughts. Will think about/look into both this afternoon.

**Comment by eswan18** [comment]
Made changes to address point 1.

Re point 2: There are too many different variables to control for once we let them loose in the shell. In my opinion, our best option is to give guidance that will work in the most setups (maybe have a callout of how to deal with `print is not callable` error from Python 2) and try to give hands-on help as time allows. I will add some notes about things that may go wrong to the notebook.

This whole section involves a lot of difficult compromises between simplicity and knowledge/hands-on practice. I am open to different approaches but I think we will have to accept some in-class errors however we walk that line.

**Comment by eswan18** [comment]
update: did some testing and it looks like my memory is faulty, `print(3)` is valid Python 2.7 syntax – that means we shouldn't get errors running code examples from this notebook in Python 2.

**Comment by markroepke** [comment]
Okay, good to know. I do think that it's important to include some information about accessing different versions of Python, though. They may not get errors in this notebook, but they will at some point.

**Comment by eswan18** [comment]
I will add a note on that to Kernels and Environments, which is really where it belongs I think.

**Comment by eswan18** [comment]
Added note on Python versions to 07-Kernels_and_Environments
