### ISSUE TITLE
Section: Kernels and Environments

### ISSUE THREAD

**Issue by markroepke** [uc-python/intermediate-python-datasci#11]

**Comment by eswan18** [comment]
Ready for review, @markroepke

**Comment by markroepke** [comment]
This looks good. I like the sequence. A few things:

1. The Python version doesn't match here:

<img width="1258" alt="Screen Shot 2019-06-23 at 6 09 01 AM" src="https://user-images.githubusercontent.com/26677807/59974800-2e7ef180-957e-11e9-951e-514770649c56.png">

2. I like these exercises, but what do you think about breaking them up and spreading the questions throughout the section? I feel like this concept may be foreign to much of the class, and I think they may find it helpful to tackle these things in chunks. For example, create an environment and install pandas in it as two separate exercises in an earlier Your Turn, and then the kernel where it currently is. I realize this is picky, but I feel it may keep people engaged and make it easier to digest.

<img width="1518" alt="Screen Shot 2019-06-23 at 6 12 33 AM" src="https://user-images.githubusercontent.com/26677807/59974804-45bddf00-957e-11e9-9c02-8db6d123d7c3.png">

3. Is it worth mentioning creating from `environment.yml`? I trust your judgment on this, but I find myself preferring this method. It could even just be one slide with an example and you could talk about the benefits of sharing environments, etc.

**Comment by eswan18** [comment]
All of the above make sense to me; I will go back through and make updates.

**Comment by eswan18** [comment]
Updated. See what you think.

**Comment by markroepke** [comment]
Thanks. Merged.
