### ISSUE TITLE
Section: Python Data Science Ecosystem

### ISSUE THREAD

**Issue by markroepke** [uc-python/intermediate-python-datasci#12]

**Comment by eswan18** [comment]
Ready for review, @markroepke 

This content is quite a bit shorter than other sections. I expect to spend 10 minutes or so on each diagram discussing what's on there, and also I'm allowing some time for questions throughout.

**Comment by markroepke** [comment]
This is a good overview. Overall, I'm happy with it. A few thoughts but not that important:

1. Do you want to center the diagrams? I think it looks better when they're on a slide on their own. (Sorry.)

2. Would it be worth creating a diagram with key categories (data science processing, statistics, machine learning, visualization, data connections, web development, web scraping, etc.) and their most important/useful packages that they could refer to later? I feel like the diagrams shown are helpful for context, but the first isn't really providing the purpose of each package and the second is pretty comprehensive -- I feel like we could cut through the noise and provide a good diagram for the majority of their purposes.

**Comment by eswan18** [comment]
I like presenting the diagrams for a couple of reasons, though I'm open to alternative ideas.
1. It shows them how much the ecosystem has changed, which tools are reliable classics and which are upstarts. A sense of how the Python ecosystem progresses (and how quickly) is important.
2. It lets the presenter call out not just the packages he likes but also ones that seem relevant based on questions that have come up in the class so far – and students have the chance to ask questions about anything that catches their eye.

I'm hoping this can be a pretty interactive session where we spend time on the packages that people could use, based on the audience. I called out the ones that are obviously useful for certain tasks many people will encounter.

If you think it would help, I could create a short "cheat sheet" slide at the end, more for them to refer back to than to talk from during the course.

**Comment by eswan18** [comment]
Also, I centered the images.

**Comment by markroepke** [comment]
Okay, I agree with everything you've said. I do think the cheatsheet is a good idea - I can merge following that addition, unless you tell me you don't want to do it.

And thanks for centering the images.

**Comment by eswan18** [comment]
Perfect — yeah, feel free to merge and I’ll work on the cheat sheet later this week.

**Comment by markroepke** [comment]
Okay, I'll merge -- when you complete it, commit it and I can merge again. I think it's a good idea to have it incorporated into the end of this section.

**Comment by markroepke** [comment]
Any update on this cheatsheet?

**Comment by eswan18** [comment]
Will have that and the cheat sheet this evening

**Comment by eswan18** [comment]
Updated, merged to develop. Closing.
