### ISSUE TITLE
Section: Modeling with scikit-learn

### ISSUE THREAD

**Issue by markroepke** [uc-python/intermediate-python-datasci#13]

**Comment by markroepke** [comment]
Ready for review in `mark-queue`, @eswan18. Note that the material felt too dense for exercises. I went for establishing a mental model of the field and then walking through a simple but relatively comprehensive and represented applied example.

**Comment by eswan18** [comment]
Open to your judgment on this, but I think using "predict" as the verb for all supervised learning examples could be misleading. Predicting -- particularly for people unfamiliar with data science -- carries a connotation of [predicting] the future. In some cases you're merely labeling (the cucumber example).

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/3449508/59847274-1023b680-9330-11e9-95f0-7142b9a9d6a1.png">

**Comment by eswan18** [comment]
Typo: "categogies"

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/3449508/59847351-3fd2be80-9330-11e9-853c-9eb0e687f06d.png">

**Comment by eswan18** [comment]
Typo: turns out "categories" is a challenging word

<img width="965" alt="image" src="https://user-images.githubusercontent.com/3449508/59847383-5416bb80-9330-11e9-88c8-685c4d58c8fa.png">

**Comment by eswan18** [comment]
Need a comma after "origin"

<img width="1503" alt="image" src="https://user-images.githubusercontent.com/3449508/59847654-15cdcc00-9331-11e9-8681-5cbb1c28988b.png">

Sorry for nitpicking but it makes a difference for clarity.

**Comment by eswan18** [comment]
If we're going to use comprehensions (which I don't think we've covered in the material), it would be clearer to use the comprehension in a previous cell (`cols = [feature for feature in train_flights_df.columns if feature != 'dep_delay]`; print(cols)`) so students can better see what's happening here.

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/3449508/59847855-b1f7d300-9331-11e9-83ca-d5f25adef5be.png">

**Comment by eswan18** [comment]
Overall, despite all my comments, I think you did a really good job in this section, distilling an extremely complex topic into a digestible overview.

**Comment by markroepke** [comment]
Sorry -- I now realize I didn't proofread this one. I agree with all of your comments, and thanks. I'll make the changes and push to `mark-queue` today.

Of note, comprehensions are covered at the end of iteration for exposure but I don't believe we have any exercises.

**Comment by markroepke** [comment]
All of these updates have been made and are ready for merge.

**Comment by eswan18** [comment]
One more typo, I should have seen this earlier:
<img width="537" alt="image" src="https://user-images.githubusercontent.com/3449508/59920129-88a17a80-93f7-11e9-8c8f-a96adc77a151.png">

**Comment by markroepke** [comment]
Good catch. Fixed and committed to `mark-queue`.

**Comment by eswan18** [comment]
Merged. Not a fast-forward, but no conflicts.
