### ISSUE TITLE
Section: Case Study, pt. 2

### ISSUE THREAD

**Issue by markroepke** [uc-python/intermediate-python-datasci#14]

**Comment by markroepke** [comment]
FYI, I'm waiting on this until I see what you're doing in Case Study, pt. 1, and the morning of the second day. It shouldn't be too hard to develop something. I'm leaning toward having them take their work from the Case Study, pt. 1, making a conda environment for it, converting it to a `.py` file, and then running the file via command line and saving results -- assuming that's all covered.  

I'll also probably add an iteration to the end of the modeling exercise.

**Comment by eswan18** [comment]
Created and merged. Review today if you have a chance.

**Comment by eswan18** [comment]
Reviewed your changes, they look good. Merged to develop. Will merge to master later today.
