### ISSUE TITLE
Issue to be resolved for first iteration

### ISSUE THREAD

**Issue by markroepke** [uc-python/intermediate-python-datasci#15]
- 00-Introduction
  - [x] CSS is not rendering
- 01-Setting_the_Stage
  - [x] CSS is not rendering
- 02-Conditionals
  - [x] CSS is not rendering
- 03-Iteration
  - [x] CSS is not rendering
- 04-Functions
  - [x] CSS is not rendering
  - [x] Slides do not open automatically
  - [x] Slide transitions are not disabled
- 05-Applying_Functions_to_DataFrames
  - [x] CSS is not rendering
  - [x] Slides do not open automatically
  - [x] Slide transitions are not disabled
- 06-Python_from_the_Shell
  - [x] CSS is not rendering
  - [x] Slides do not open automatically
  - [x] Slide transitions are not disabled
  - [x] Images not appearing, files don't appear to be in `notebooks/images`
- 07-Kernels_and_Environments
  - [x] CSS is not rendering
  - [x] Slides do not open automatically
  - [x] Slide transitions are not disabled
  - [x] Images not appearing, files don't appear to be in `notebooks/images`
  - [x] `uc-python` kernel not available in Binder container
- 08-Python_Data_Sci_Ecosystem.ipynb
  - [x] CSS is not rendering
  - [x] Slides do not open automatically
  - [x] Slide transitions are not disabled
  - [x] Images not appearing, files don't appear to be in `notebooks/images`
- 09-Modeling
  - [x] CSS is not rendering
  - [x] No `sklearn` in environment

**Comment by markroepke** [comment]
`sklearn` has been added to the environment and added to `mark-queue` -- ready for merge to `develop`

**Comment by markroepke** [comment]
CSS rendering has been fixed and is in `mark-queue`

**Comment by markroepke** [comment]
Slide metadata has been updated and is in `mark-queue`

**Comment by markroepke** [comment]
Added to postBuild to make `uc-python` kernel available in Binder, in `mark-queue`

**Comment by markroepke** [comment]
Images now in `mark-queue`. A merge of `mark-queue` to `develop` and `develop` to `master` should fix all of these issues.

**Comment by eswan18** [comment]
Thanks for taking care of this. Reviewing now and then I'll merge.

**Comment by eswan18** [comment]
Merged to master. Closing issue.
