### ISSUE TITLE
Proofread for April Delivery

### ISSUE THREAD

**Issue by eswan18** [uc-python/intermediate-python-datasci#24]
Just want a place to track our looking over of the material for the next delivery. At least one of us should review each notebook but ideally both.

00-Introduction.ipynb
- [x] Ethan
- [x] Brad

01-Setting_the_Stage.ipynb
- [x] Ethan
- [x] Brad

02-Conditionals.ipynb
- [x] Ethan
- [x] Brad

03-Iteration.ipynb
- [x] Ethan
- [x] Brad

04-Functions.ipynb
- [x] Ethan
- [x] Brad

05-Applying_Functions_to_DataFrames.ipynb
- [x] Ethan
- [x] Brad

06-Python_from_the_Shell.ipynb
- [x] Ethan
- [x] Brad

07-Kernels_and_Environments.ipynb
- [x] Ethan
- [x] Brad

08-Python_Data_Sci_Ecosystem.ipynb
- [x] Ethan
- [x] Brad

09-Modeling.ipynb
- [x] Ethan
- [x] Brad

99-Closing.ipynb
- [x] Ethan
- [x] Brad

Case Study Solutions.ipynb
- [ ] Ethan
- [ ] Brad

Case Study.ipynb
- [x] Ethan
- [ ] Brad

**Comment by eswan18** [comment]
@bradleyboehmke Can we close this up? Seems like you've looked over everything.

**Comment by bradleyboehmke** [comment]
Yep
