### ISSUE TITLE
Division of Content for Delivery

### ISSUE THREAD

**Issue by eswan18** [uc-python/intermediate-python-datasci#31]
I think we discussed this in an email at one point but I wasn't able to track it down. I've listed some tentative assignments below, but I'm open to however we want to do it.

| Section | Lecturer |
|:------|:------|
| 00-Introduction.ipynb | ? |
| 01-Setting_the_Stage.ipynb | ? |
| 02-Conditionals.ipynb | ? |
| 03-Iteration.ipynb | ? |
| 04-Functions.ipynb | ? |
| 05-Applying_Functions_to_DataFrames.ipynb | ? |
| 06-Python_from_the_Shell.ipynb | Ethan |
| 07-Kernels_and_Environments.ipynb | Ethan |
| 08-Python_Data_Sci_Ecosystem.ipynb | ? |
| 09-Modeling.ipynb | Brad |

**Comment by bradleyboehmke** [comment]
The below is one proposal. This would have us both teaching something each day, with the exception of day 4 (unless you help out with the case study).

| Section | Lecturer |
|:------|:------|
| 00-Introduction.ipynb | Brad |
| 01-Setting_the_Stage.ipynb | Ethan |
| 02-Conditionals.ipynb | Ethan |
| 03-Iteration.ipynb | Brad |
| 04-Functions.ipynb | Brad |
| 05-Applying_Functions_to_DataFrames.ipynb | Ethan |
| 06-Python_from_the_Shell.ipynb | Ethan |
| 07-Kernels_and_Environments.ipynb | Ethan |
| 08-Python_Data_Sci_Ecosystem.ipynb | Brad |
| 09-Modeling.ipynb | Brad |

**Comment by eswan18** [comment]
I hadn't thought much about the case or where the breaks fall. Below is a more complete version of the schedule. I like your plan – the only adjustment I made was assigning myself to review the first case study and you to review the second (I figured that made sense to keep you with the modeling-heavy part).

This means:
- Day 1 is 50/50
- Day 2 is 50/50
- Day 3 is mostly me, you do 30 minutes
- Day 4 is all you, but a lot of the time is spent doing the case

| Section | Lecturer |
|:------|:------|
| 00-Introduction.ipynb | Brad |
| 01-Setting_the_Stage.ipynb | Ethan |
| 02-Conditionals.ipynb | Ethan |
| 03-Iteration.ipynb | Brad |
| day break | -- |
| 04-Functions.ipynb | Brad |
| 05-Applying_Functions_to_DataFrames.ipynb | Ethan |
| Case Study | -- |
| day break | -- |
| Case Study Review | Ethan |
| 06-Python_from_the_Shell.ipynb | Ethan |
| 07-Kernels_and_Environments.ipynb | Ethan |
| 08-Python_Data_Sci_Ecosystem.ipynb | Brad |
| day break | -- |
| 09-Modeling.ipynb | Brad |
| Case Study 2 | -- |
| Case Study 2 Review | Brad |

Let me know if you want to change anything above, otherwise we can go with this.

**Comment by bradleyboehmke** [comment]
This looks good to me

**Comment by eswan18** [comment]
Great, I'll close this out.
