### ISSUE TITLE
Section: Setting the Stage

### ISSUE THREAD

**Issue by markroepke** [uc-python/intermediate-python-datasci#4]

**Comment by markroepke** [comment]
@eswan18, How would you feel about renaming this section to something like "Setting the Stage" or "Introductory Review" rather than being `pandas`-specific? I think it'd be useful to review lists and dictionaries here, so I'd like to be more generic.

**Comment by markroepke** [comment]
Ready for review, @eswan18.

**Comment by eswan18** [comment]
Small typo
<img width="758" alt="image" src="https://user-images.githubusercontent.com/3449508/59568016-e6724300-9042-11e9-85b7-3ef0c58185f6.png">

**Comment by eswan18** [comment]
Overall I'm very happy with this section and will close this issue once the typo (above) is fixed.

**Comment by markroepke** [comment]
Thanks, made fixes and ready for merge to develop.

**Comment by eswan18** [comment]
Merged
