### ISSUE TITLE
Section: Conditionals

### ISSUE THREAD

**Issue by markroepke** [uc-python/intermediate-python-datasci#5]

**Comment by markroepke** [comment]
Ready for review, @eswan18.

**Comment by eswan18** [comment]
I think a non-counting example would be a good supplement to the current examples here:
<img width="465" alt="image" src="https://user-images.githubusercontent.com/3449508/59568085-d149e400-9043-11e9-95b6-da8e9bf730cc.png">

Perhaps "Keep walking down this road until you hit 5th Street."

**Comment by eswan18** [comment]
I think a non-counting example would be a good supplement to the current examples here:
<img width="465" alt="image" src="https://user-images.githubusercontent.com/3449508/59568085-d149e400-9043-11e9-95b6-da8e9bf730cc.png">

Perhaps "Keep walking down this road until you hit 5th Street."

**Comment by eswan18** [comment]
Otherwise this looks good

**Comment by markroepke** [comment]
Thanks, made fixes and ready for merge to develop.

**Comment by eswan18** [comment]
Merged
