### ISSUE TITLE
Section: Functions

### ISSUE THREAD

**Issue by markroepke** [uc-python/intermediate-python-datasci#7]

**Comment by eswan18** [comment]
Ready for review, @markroepke

**Comment by markroepke** [comment]
Overall, this looks really good. I have two small comments:

1. Should we include something about parameter specification/argument order when passing arguments to a function? I'm flexible on this, but it could be worth calling out to a nonprogramming audience.
2. I think it makes sense to move the lambda/anonymous function to be after the final Your Turn exercises. There's nothing about lambda functions in those exercises, and I view lambda functions as a "nice to know" for this module, but I think it's important the skills in the Your Turn exercises get the appropriate focus.

Thoughts?

**Comment by eswan18** [comment]
On the former, I also have mixed feelings. In the current version (arguments by order only) it’s clear that argument order is important. Keyword arguments are handy but they add quite a bit of complexity.

What I hadn’t thought of until now is that there are some cases where we need to use keyword args (customizations like `sep` in `pd.read_csv`) so it’s probably worth adding them. I’ll try to do that later today. 

On the latter, I agree and will make that change.

**Comment by eswan18** [comment]
Made updates and re-pushed to `ethan-queue`

**Comment by markroepke** [comment]
Merged
